export const GENRE_REQUEST = 'GENRE_REQUEST';
export const GENRE_SUCCESS = 'GENRE_SUCCESS';
export const GENRE_FAIL = 'GENRE_FAIL';

export const TOP_CHARTS_REQUEST = 'TOP_CHARTS_REQUEST';
export const TOP_CHARTS_SUCCESS = 'TOP_CHARTS_SUCCESS';
export const TOP_CHARTS_FAIL = 'TOP_CHARTS_FAIL';