export const GENRE_REQUEST = 'GENRE_REQUEST';
export const GENRE_SUCCESS = 'GENRE_SUCCESS';
export const GENRE_FAIL = 'GENRE_FAIL';

export const TOP_CHARTS_REQUEST = 'TOP_CHARTS_REQUEST';
export const TOP_CHARTS_SUCCESS = 'TOP_CHARTS_SUCCESS';
export const TOP_CHARTS_FAIL = 'TOP_CHARTS_FAIL';

export const GET_TRACK_REQUEST = 'GET_TRACK_REQUEST';
export const GET_TRACK_SUCCESS = 'GET_TRACK_SUCCESS';
export const GET_TRACK_FAIL = 'GET_TRACK_FAIL';

export const GET_RELATED_TRACKS_REQUEST = 'GET_RELATED_TRACKS_REQUEST';
export const GET_RELATED_TRACKS_SUCCESS = 'GET_RELATED_TRACKS_SUCCESS';
export const GET_RELATED_TRACKS_FAIL = 'GET_RELATED_TRACKS_FAIL';